# FOX Library Public Header Files
# This file contains the complete list of public header files for the FOX toolkit library
# All headers are prefixed with ${FOX_HEADERS_DIR} which should point to the include directory

set(FOX_HEADERS
    ${FOX_HEADERS_DIR}/FX4Splitter.h
    ${FOX_HEADERS_DIR}/FX7Segment.h
    ${FOX_HEADERS_DIR}/FX885910Codec.h
    ${FOX_HEADERS_DIR}/FX885911Codec.h
    ${FOX_HEADERS_DIR}/FX885913Codec.h
    ${FOX_HEADERS_DIR}/FX885914Codec.h
    ${FOX_HEADERS_DIR}/FX885915Codec.h
    ${FOX_HEADERS_DIR}/FX885916Codec.h
    ${FOX_HEADERS_DIR}/FX88591Codec.h
    ${FOX_HEADERS_DIR}/FX88592Codec.h
    ${FOX_HEADERS_DIR}/FX88593Codec.h
    ${FOX_HEADERS_DIR}/FX88594Codec.h
    ${FOX_HEADERS_DIR}/FX88595Codec.h
    ${FOX_HEADERS_DIR}/FX88596Codec.h
    ${FOX_HEADERS_DIR}/FX88597Codec.h
    ${FOX_HEADERS_DIR}/FX88598Codec.h
    ${FOX_HEADERS_DIR}/FX88599Codec.h
    ${FOX_HEADERS_DIR}/FXAccelTable.h
    ${FOX_HEADERS_DIR}/FXApp.h
    ${FOX_HEADERS_DIR}/FXArray.h
    ${FOX_HEADERS_DIR}/FXArrowButton.h
    ${FOX_HEADERS_DIR}/FXAtomic.h
    ${FOX_HEADERS_DIR}/FXAutoPtr.h
    ${FOX_HEADERS_DIR}/FXAutoThreadStorageKey.h
    ${FOX_HEADERS_DIR}/FXBMPIcon.h
    ${FOX_HEADERS_DIR}/FXBMPImage.h
    ${FOX_HEADERS_DIR}/FXBZFileStream.h
    ${FOX_HEADERS_DIR}/FXBarrier.h
    ${FOX_HEADERS_DIR}/FXBitmap.h
    ${FOX_HEADERS_DIR}/FXBitmapFrame.h
    ${FOX_HEADERS_DIR}/FXBitmapView.h
    ${FOX_HEADERS_DIR}/FXButton.h
    ${FOX_HEADERS_DIR}/FXCP1250Codec.h
    ${FOX_HEADERS_DIR}/FXCP1251Codec.h
    ${FOX_HEADERS_DIR}/FXCP1252Codec.h
    ${FOX_HEADERS_DIR}/FXCP1253Codec.h
    ${FOX_HEADERS_DIR}/FXCP1254Codec.h
    ${FOX_HEADERS_DIR}/FXCP1255Codec.h
    ${FOX_HEADERS_DIR}/FXCP1256Codec.h
    ${FOX_HEADERS_DIR}/FXCP1257Codec.h
    ${FOX_HEADERS_DIR}/FXCP1258Codec.h
    ${FOX_HEADERS_DIR}/FXCP437Codec.h
    ${FOX_HEADERS_DIR}/FXCP850Codec.h
    ${FOX_HEADERS_DIR}/FXCP852Codec.h
    ${FOX_HEADERS_DIR}/FXCP855Codec.h
    ${FOX_HEADERS_DIR}/FXCP856Codec.h
    ${FOX_HEADERS_DIR}/FXCP857Codec.h
    ${FOX_HEADERS_DIR}/FXCP860Codec.h
    ${FOX_HEADERS_DIR}/FXCP861Codec.h
    ${FOX_HEADERS_DIR}/FXCP862Codec.h
    ${FOX_HEADERS_DIR}/FXCP863Codec.h
    ${FOX_HEADERS_DIR}/FXCP864Codec.h
    ${FOX_HEADERS_DIR}/FXCP865Codec.h
    ${FOX_HEADERS_DIR}/FXCP866Codec.h
    ${FOX_HEADERS_DIR}/FXCP869Codec.h
    ${FOX_HEADERS_DIR}/FXCP874Codec.h
    ${FOX_HEADERS_DIR}/FXCURCursor.h
    ${FOX_HEADERS_DIR}/FXCalendar.h
    ${FOX_HEADERS_DIR}/FXCalendarView.h
    ${FOX_HEADERS_DIR}/FXCallback.h
    ${FOX_HEADERS_DIR}/FXCanvas.h
    ${FOX_HEADERS_DIR}/FXCheckButton.h
    ${FOX_HEADERS_DIR}/FXChoiceBox.h
    ${FOX_HEADERS_DIR}/FXColorBar.h
    ${FOX_HEADERS_DIR}/FXColorDialog.h
    ${FOX_HEADERS_DIR}/FXColorList.h
    ${FOX_HEADERS_DIR}/FXColorRing.h
    ${FOX_HEADERS_DIR}/FXColorSelector.h
    ${FOX_HEADERS_DIR}/FXColorWell.h
    ${FOX_HEADERS_DIR}/FXColorWheel.h
    ${FOX_HEADERS_DIR}/FXColors.h
    ${FOX_HEADERS_DIR}/FXComboBox.h
    ${FOX_HEADERS_DIR}/FXCompletion.h
    ${FOX_HEADERS_DIR}/FXComplexd.h
    ${FOX_HEADERS_DIR}/FXComplexf.h
    ${FOX_HEADERS_DIR}/FXComposeContext.h
    ${FOX_HEADERS_DIR}/FXComposite.h
    ${FOX_HEADERS_DIR}/FXCondition.h
    ${FOX_HEADERS_DIR}/FXConsole.h
    ${FOX_HEADERS_DIR}/FXCursor.h
    ${FOX_HEADERS_DIR}/FXDC.h
    ${FOX_HEADERS_DIR}/FXDCPrint.h
    ${FOX_HEADERS_DIR}/FXDCWindow.h
    ${FOX_HEADERS_DIR}/FXDDSIcon.h
    ${FOX_HEADERS_DIR}/FXDDSImage.h
    ${FOX_HEADERS_DIR}/FXDLL.h
    ${FOX_HEADERS_DIR}/FXDataTarget.h
    ${FOX_HEADERS_DIR}/FXDate.h
    ${FOX_HEADERS_DIR}/FXDebugTarget.h
    ${FOX_HEADERS_DIR}/FXDelegator.h
    ${FOX_HEADERS_DIR}/FXDial.h
    ${FOX_HEADERS_DIR}/FXDialogBox.h
    ${FOX_HEADERS_DIR}/FXDictionary.h
    ${FOX_HEADERS_DIR}/FXDictionaryOf.h
    ${FOX_HEADERS_DIR}/FXDir.h
    ${FOX_HEADERS_DIR}/FXDirBox.h
    ${FOX_HEADERS_DIR}/FXDirDialog.h
    ${FOX_HEADERS_DIR}/FXDirList.h
    ${FOX_HEADERS_DIR}/FXDirSelector.h
    ${FOX_HEADERS_DIR}/FXDirVisitor.h
    ${FOX_HEADERS_DIR}/FXDirWatch.h
    ${FOX_HEADERS_DIR}/FXDispatcher.h
    ${FOX_HEADERS_DIR}/FXDisplay.h
    ${FOX_HEADERS_DIR}/FXDockBar.h
    ${FOX_HEADERS_DIR}/FXDockHandler.h
    ${FOX_HEADERS_DIR}/FXDockSite.h
    ${FOX_HEADERS_DIR}/FXDockTitle.h
    ${FOX_HEADERS_DIR}/FXDocument.h
    ${FOX_HEADERS_DIR}/FXDragCorner.h
    ${FOX_HEADERS_DIR}/FXDrawable.h
    ${FOX_HEADERS_DIR}/FXDriveBox.h
    ${FOX_HEADERS_DIR}/FXEXEIcon.h
    ${FOX_HEADERS_DIR}/FXEXEImage.h
    ${FOX_HEADERS_DIR}/FXElement.h
    ${FOX_HEADERS_DIR}/FXEvent.h
    ${FOX_HEADERS_DIR}/FXEventDispatcher.h
    ${FOX_HEADERS_DIR}/FXEventLoop.h
    ${FOX_HEADERS_DIR}/FXException.h
    ${FOX_HEADERS_DIR}/FXExpression.h
    ${FOX_HEADERS_DIR}/FXExtentd.h
    ${FOX_HEADERS_DIR}/FXExtentf.h
    ${FOX_HEADERS_DIR}/FXFile.h
    ${FOX_HEADERS_DIR}/FXFileAssociations.h
    ${FOX_HEADERS_DIR}/FXFileDialog.h
    ${FOX_HEADERS_DIR}/FXFileList.h
    ${FOX_HEADERS_DIR}/FXFileProgressDialog.h
    ${FOX_HEADERS_DIR}/FXFileSelector.h
    ${FOX_HEADERS_DIR}/FXFileStream.h
    ${FOX_HEADERS_DIR}/FXFoldingList.h
    ${FOX_HEADERS_DIR}/FXFont.h
    ${FOX_HEADERS_DIR}/FXFontDialog.h
    ${FOX_HEADERS_DIR}/FXFontSelector.h
    ${FOX_HEADERS_DIR}/FXFrame.h
    ${FOX_HEADERS_DIR}/FXGIFCursor.h
    ${FOX_HEADERS_DIR}/FXGIFIcon.h
    ${FOX_HEADERS_DIR}/FXGIFImage.h
    ${FOX_HEADERS_DIR}/FXGLCanvas.h
    ${FOX_HEADERS_DIR}/FXGLContext.h
    ${FOX_HEADERS_DIR}/FXGLObject.h
    ${FOX_HEADERS_DIR}/FXGLViewer.h
    ${FOX_HEADERS_DIR}/FXGLVisual.h
    ${FOX_HEADERS_DIR}/FXGZFileStream.h
    ${FOX_HEADERS_DIR}/FXGauge.h
    ${FOX_HEADERS_DIR}/FXGradientBar.h
    ${FOX_HEADERS_DIR}/FXGroupBox.h
    ${FOX_HEADERS_DIR}/FXHash.h
    ${FOX_HEADERS_DIR}/FXHashOf.h
    ${FOX_HEADERS_DIR}/FXHeader.h
    ${FOX_HEADERS_DIR}/FXHorizontalFrame.h
    ${FOX_HEADERS_DIR}/FXICOIcon.h
    ${FOX_HEADERS_DIR}/FXICOImage.h
    ${FOX_HEADERS_DIR}/FXIFFIcon.h
    ${FOX_HEADERS_DIR}/FXIFFImage.h
    ${FOX_HEADERS_DIR}/FXINI.h
    ${FOX_HEADERS_DIR}/FXINIFile.h
    ${FOX_HEADERS_DIR}/FXIO.h
    ${FOX_HEADERS_DIR}/FXIOBuffer.h
    ${FOX_HEADERS_DIR}/FXIODevice.h
    ${FOX_HEADERS_DIR}/FXIcon.h
    ${FOX_HEADERS_DIR}/FXIconCache.h
    ${FOX_HEADERS_DIR}/FXIconList.h
    ${FOX_HEADERS_DIR}/FXIconSource.h
    ${FOX_HEADERS_DIR}/FXId.h
    ${FOX_HEADERS_DIR}/FXImage.h
    ${FOX_HEADERS_DIR}/FXImageFrame.h
    ${FOX_HEADERS_DIR}/FXImageView.h
    ${FOX_HEADERS_DIR}/FXInputDialog.h
    ${FOX_HEADERS_DIR}/FXJP2Icon.h
    ${FOX_HEADERS_DIR}/FXJP2Image.h
    ${FOX_HEADERS_DIR}/FXJPGIcon.h
    ${FOX_HEADERS_DIR}/FXJPGImage.h
    ${FOX_HEADERS_DIR}/FXJSON.h
    ${FOX_HEADERS_DIR}/FXJSONFile.h
    ${FOX_HEADERS_DIR}/FXJSONString.h
    ${FOX_HEADERS_DIR}/FXKOI8RCodec.h
    ${FOX_HEADERS_DIR}/FXKnob.h
    ${FOX_HEADERS_DIR}/FXLFQueue.h
    ${FOX_HEADERS_DIR}/FXLabel.h
    ${FOX_HEADERS_DIR}/FXList.h
    ${FOX_HEADERS_DIR}/FXListBox.h
    ${FOX_HEADERS_DIR}/FXLocale.h
    ${FOX_HEADERS_DIR}/FXMDIButton.h
    ${FOX_HEADERS_DIR}/FXMDIChild.h
    ${FOX_HEADERS_DIR}/FXMDIClient.h
    ${FOX_HEADERS_DIR}/FXMainWindow.h
    ${FOX_HEADERS_DIR}/FXMappedFile.h
    ${FOX_HEADERS_DIR}/FXMarkedPtr.h
    ${FOX_HEADERS_DIR}/FXMat2d.h
    ${FOX_HEADERS_DIR}/FXMat2f.h
    ${FOX_HEADERS_DIR}/FXMat3d.h
    ${FOX_HEADERS_DIR}/FXMat3f.h
    ${FOX_HEADERS_DIR}/FXMat4d.h
    ${FOX_HEADERS_DIR}/FXMat4f.h
    ${FOX_HEADERS_DIR}/FXMatrix.h
    ${FOX_HEADERS_DIR}/FXMemoryStream.h
    ${FOX_HEADERS_DIR}/FXMenuBar.h
    ${FOX_HEADERS_DIR}/FXMenuButton.h
    ${FOX_HEADERS_DIR}/FXMenuCaption.h
    ${FOX_HEADERS_DIR}/FXMenuCascade.h
    ${FOX_HEADERS_DIR}/FXMenuCheck.h
    ${FOX_HEADERS_DIR}/FXMenuCommand.h
    ${FOX_HEADERS_DIR}/FXMenuPane.h
    ${FOX_HEADERS_DIR}/FXMenuRadio.h
    ${FOX_HEADERS_DIR}/FXMenuSeparator.h
    ${FOX_HEADERS_DIR}/FXMenuTitle.h
    ${FOX_HEADERS_DIR}/FXMessageBox.h
    ${FOX_HEADERS_DIR}/FXMessageChannel.h
    ${FOX_HEADERS_DIR}/FXMetaClass.h
    ${FOX_HEADERS_DIR}/FXMutex.h
    ${FOX_HEADERS_DIR}/FXObject.h
    ${FOX_HEADERS_DIR}/FXObjectList.h
    ${FOX_HEADERS_DIR}/FXOptionMenu.h
    ${FOX_HEADERS_DIR}/FXPCXIcon.h
    ${FOX_HEADERS_DIR}/FXPCXImage.h
    ${FOX_HEADERS_DIR}/FXPNGIcon.h
    ${FOX_HEADERS_DIR}/FXPNGImage.h
    ${FOX_HEADERS_DIR}/FXPPMIcon.h
    ${FOX_HEADERS_DIR}/FXPPMImage.h
    ${FOX_HEADERS_DIR}/FXPacker.h
    ${FOX_HEADERS_DIR}/FXParallel.h
    ${FOX_HEADERS_DIR}/FXParseBuffer.h
    ${FOX_HEADERS_DIR}/FXPath.h
    ${FOX_HEADERS_DIR}/FXPerformance.h
    ${FOX_HEADERS_DIR}/FXPicker.h
    ${FOX_HEADERS_DIR}/FXPipe.h
    ${FOX_HEADERS_DIR}/FXPoint.h
    ${FOX_HEADERS_DIR}/FXPopup.h
    ${FOX_HEADERS_DIR}/FXPrintDialog.h
    ${FOX_HEADERS_DIR}/FXProcess.h
    ${FOX_HEADERS_DIR}/FXProgressBar.h
    ${FOX_HEADERS_DIR}/FXProgressDialog.h
    ${FOX_HEADERS_DIR}/FXPtrList.h
    ${FOX_HEADERS_DIR}/FXPtrQueue.h
    ${FOX_HEADERS_DIR}/FXQOIFIcon.h
    ${FOX_HEADERS_DIR}/FXQOIFImage.h
    ${FOX_HEADERS_DIR}/FXQuatd.h
    ${FOX_HEADERS_DIR}/FXQuatf.h
    ${FOX_HEADERS_DIR}/FXRASIcon.h
    ${FOX_HEADERS_DIR}/FXRASImage.h
    ${FOX_HEADERS_DIR}/FXRGBIcon.h
    ${FOX_HEADERS_DIR}/FXRGBImage.h
    ${FOX_HEADERS_DIR}/FXRadioButton.h
    ${FOX_HEADERS_DIR}/FXRandom.h
    ${FOX_HEADERS_DIR}/FXRangeSlider.h
    ${FOX_HEADERS_DIR}/FXRanged.h
    ${FOX_HEADERS_DIR}/FXRangef.h
    ${FOX_HEADERS_DIR}/FXReactor.h
    ${FOX_HEADERS_DIR}/FXReadWriteLock.h
    ${FOX_HEADERS_DIR}/FXRealSlider.h
    ${FOX_HEADERS_DIR}/FXRealSpinner.h
    ${FOX_HEADERS_DIR}/FXRecentFiles.h
    ${FOX_HEADERS_DIR}/FXRectangle.h
    ${FOX_HEADERS_DIR}/FXRefPtr.h
    ${FOX_HEADERS_DIR}/FXRegion.h
    ${FOX_HEADERS_DIR}/FXRegistry.h
    ${FOX_HEADERS_DIR}/FXReplaceDialog.h
    ${FOX_HEADERS_DIR}/FXReverseDictionary.h
    ${FOX_HEADERS_DIR}/FXReverseDictionaryOf.h
    ${FOX_HEADERS_DIR}/FXRex.h
    ${FOX_HEADERS_DIR}/FXRootWindow.h
    ${FOX_HEADERS_DIR}/FXRuler.h
    ${FOX_HEADERS_DIR}/FXRulerView.h
    ${FOX_HEADERS_DIR}/FXRunnable.h
    ${FOX_HEADERS_DIR}/FXScopedThread.h
    ${FOX_HEADERS_DIR}/FXScrollArea.h
    ${FOX_HEADERS_DIR}/FXScrollBar.h
    ${FOX_HEADERS_DIR}/FXScrollPane.h
    ${FOX_HEADERS_DIR}/FXScrollWindow.h
    ${FOX_HEADERS_DIR}/FXSearchDialog.h
    ${FOX_HEADERS_DIR}/FXSemaQueue.h
    ${FOX_HEADERS_DIR}/FXSemaphore.h
    ${FOX_HEADERS_DIR}/FXSeparator.h
    ${FOX_HEADERS_DIR}/FXSettings.h
    ${FOX_HEADERS_DIR}/FXShell.h
    ${FOX_HEADERS_DIR}/FXShutter.h
    ${FOX_HEADERS_DIR}/FXSize.h
    ${FOX_HEADERS_DIR}/FXSlider.h
    ${FOX_HEADERS_DIR}/FXSocket.h
    ${FOX_HEADERS_DIR}/FXSphered.h
    ${FOX_HEADERS_DIR}/FXSpheref.h
    ${FOX_HEADERS_DIR}/FXSpinLock.h
    ${FOX_HEADERS_DIR}/FXSpinner.h
    ${FOX_HEADERS_DIR}/FXSplashWindow.h
    ${FOX_HEADERS_DIR}/FXSplitter.h
    ${FOX_HEADERS_DIR}/FXSpring.h
    ${FOX_HEADERS_DIR}/FXStat.h
    ${FOX_HEADERS_DIR}/FXStatusBar.h
    ${FOX_HEADERS_DIR}/FXStatusLine.h
    ${FOX_HEADERS_DIR}/FXStream.h
    ${FOX_HEADERS_DIR}/FXString.h
    ${FOX_HEADERS_DIR}/FXStringDictionary.h
    ${FOX_HEADERS_DIR}/FXSwitcher.h
    ${FOX_HEADERS_DIR}/FXSystem.h
    ${FOX_HEADERS_DIR}/FXTGAIcon.h
    ${FOX_HEADERS_DIR}/FXTGAImage.h
    ${FOX_HEADERS_DIR}/FXTIFIcon.h
    ${FOX_HEADERS_DIR}/FXTIFImage.h
    ${FOX_HEADERS_DIR}/FXTabBar.h
    ${FOX_HEADERS_DIR}/FXTabBook.h
    ${FOX_HEADERS_DIR}/FXTabItem.h
    ${FOX_HEADERS_DIR}/FXTable.h
    ${FOX_HEADERS_DIR}/FXTaskGroup.h
    ${FOX_HEADERS_DIR}/FXText.h
    ${FOX_HEADERS_DIR}/FXTextCodec.h
    ${FOX_HEADERS_DIR}/FXTextField.h
    ${FOX_HEADERS_DIR}/FXThread.h
    ${FOX_HEADERS_DIR}/FXThreadPool.h
    ${FOX_HEADERS_DIR}/FXToggleButton.h
    ${FOX_HEADERS_DIR}/FXToolBar.h
    ${FOX_HEADERS_DIR}/FXToolBarGrip.h
    ${FOX_HEADERS_DIR}/FXToolBarShell.h
    ${FOX_HEADERS_DIR}/FXToolBarTab.h
    ${FOX_HEADERS_DIR}/FXToolTip.h
    ${FOX_HEADERS_DIR}/FXTopWindow.h
    ${FOX_HEADERS_DIR}/FXTranslator.h
    ${FOX_HEADERS_DIR}/FXTreeList.h
    ${FOX_HEADERS_DIR}/FXTreeListBox.h
    ${FOX_HEADERS_DIR}/FXTriStateButton.h
    ${FOX_HEADERS_DIR}/FXURL.h
    ${FOX_HEADERS_DIR}/FXUTF16Codec.h
    ${FOX_HEADERS_DIR}/FXUTF32Codec.h
    ${FOX_HEADERS_DIR}/FXUTF8Codec.h
    ${FOX_HEADERS_DIR}/FXUndoList.h
    ${FOX_HEADERS_DIR}/FXVariant.h
    ${FOX_HEADERS_DIR}/FXVariantArray.h
    ${FOX_HEADERS_DIR}/FXVariantMap.h
    ${FOX_HEADERS_DIR}/FXVec2d.h
    ${FOX_HEADERS_DIR}/FXVec2f.h
    ${FOX_HEADERS_DIR}/FXVec3d.h
    ${FOX_HEADERS_DIR}/FXVec3f.h
    ${FOX_HEADERS_DIR}/FXVec4d.h
    ${FOX_HEADERS_DIR}/FXVec4f.h
    ${FOX_HEADERS_DIR}/FXVerticalFrame.h
    ${FOX_HEADERS_DIR}/FXVisual.h
    ${FOX_HEADERS_DIR}/FXWEBPIcon.h
    ${FOX_HEADERS_DIR}/FXWEBPImage.h
    ${FOX_HEADERS_DIR}/FXWSQueue.h
    ${FOX_HEADERS_DIR}/FXWindow.h
    ${FOX_HEADERS_DIR}/FXWizard.h
    ${FOX_HEADERS_DIR}/FXWorker.h
    ${FOX_HEADERS_DIR}/FXXBMIcon.h
    ${FOX_HEADERS_DIR}/FXXBMImage.h
    ${FOX_HEADERS_DIR}/FXXML.h
    ${FOX_HEADERS_DIR}/FXXMLFile.h
    ${FOX_HEADERS_DIR}/FXXMLString.h
    ${FOX_HEADERS_DIR}/FXXPMIcon.h
    ${FOX_HEADERS_DIR}/FXXPMImage.h
    ${FOX_HEADERS_DIR}/FXhalf.h
    ${FOX_HEADERS_DIR}/fx.h
    ${FOX_HEADERS_DIR}/fx3d.h
    ${FOX_HEADERS_DIR}/fxadler32.h
    ${FOX_HEADERS_DIR}/fxascii.h
    ${FOX_HEADERS_DIR}/fxchar.h
    ${FOX_HEADERS_DIR}/fxcpuid.h
    ${FOX_HEADERS_DIR}/fxcrc.h
    ${FOX_HEADERS_DIR}/fxdefs.h
    ${FOX_HEADERS_DIR}/fxendian.h
    ${FOX_HEADERS_DIR}/fxkeys.h
    ${FOX_HEADERS_DIR}/fxmath.h
    ${FOX_HEADERS_DIR}/fxunicode.h
    ${FOX_HEADERS_DIR}/fxver.h
    ${FOX_HEADERS_DIR}/xincs.h
)
